### ISSUE TITLE
Can't get previews to work on staging server

### ISSUE THREAD

**Issue by mortscode** [samlfair/svelte-tutorial#1]
Hey @samlfair, thanks for this tutorial. I've been able to spin up previews with my local dev environment, but for some reason, my staging server previews will not work. I've configured my SvelteKit routes and configs just like you have them here.

I'm hosting my staging server on AWS Amplify. My Prismic settings are as follows:

<img width="969" alt="Pasted_Image_8_31_21__11_07_PM" src="https://user-images.githubusercontent.com/3239582/131620548-e31d6121-6faa-40ea-88c2-13e002c43ac2.png">

The exact same configuration with `http://localhost:3000` works with preview as expected on my local build. Any ideas what file(s) or configuration might be at fault?

**Comment by samlfair** [comment]
Hey @mortscode,

I've been having some trouble with previews in Svelte myself, and it might be connected to a larger issue with previews. I need to look into it, and I'll get back to you.

**Comment by mortscode** [comment]
Awesome. Happy to help however I can. I'm relatively new to Prismic, so I'm trying to understand exactly what is required to get it up and running. As far as I can tell, the preview script is present on all my pages (as it is included in my `__layout.svelte` file). Not sure what else is needed.

**Comment by samlfair** [comment]
Hey @mortscode,

I figured this out this week, and then I remembered that I already figured it out back in May 😆 . 

https://github.com/samlfair/svelte-tutorial/compare/previews

Basically, you need to retrieve the cookie and pass it to your Client. That means doing a few things:

- Creating a `hooks.js` file so that you can customize [SvelteKit's `getSession`](https://kit.svelte.dev/docs#hooks-getsession) hook and pass the cookie to it.
- Retrieving the cookie from the `session` in the `load()` function.
- Refactoring `utils/client.js` so that it exports a function that can accept the cookie as an argument.

You can see all the changes in the compare view that I linked, but let me know if you have any questions.

Sam

**Comment by mortscode** [comment]
This is working perfectly for me on my local dev server—`npm run dev` on `localhost:3000`

However, I cannot seem to make it work with the static adapter for sveltekit. Am I dreaming that it could be a possibility? Prismic & Gatsby (also a static site) seem to have it figured out. My client is wanting that preview functionality so they can get approval on page changes before publishing updates.

I'm trying to lean into the js docs on Prismic, but can't figure it out: https://prismic.io/docs/technologies/previews-and-the-prismic-toolbar-javascript

I suppose my backup plan would be to move off AWS and over to Netlify or Render to try using SSR instead of the static adapter.

**Comment by mortscode** [comment]
I'm having no luck with Preview on Netlify either. It's deploying and rendering as expected on Netlify, but the Preview functionality isn't working for me on the `my-sitename.netlify.app` hosted url.

Have you had any luck getting the Prismic Preview to work on Netlify or any other deployment service?

**Comment by samlfair** [comment]
@mortscode I haven't looked into previewing with static. 

As far as I understand, you can't preview a statically-generated page, because it doesn't get generated by your app.

With Gatsby, Next, and Nuxt, I believe we circumvent this by launching the app in SPA mode and then redirecting to the previewed page. Basically, `/preview` is statically generated, and it redirects. So maybe `/preview` needs to be a `.svelte` component. I'll look into it.

**Comment by samlfair** [comment]
Hey @mortscode,

I refactored `/src/preview.js` to `/src/preview.svelte`. Can you tell me if this implementation works for you? It works for me locally with adapter-static.

https://github.com/samlfair/svelte-tutorial/compare/previews

What I did:
- You need to get some more information in the getSession hook in `/src/hooks/` to resolve the URL of the previewed document
- Then, I converted the preview route from a function to a component. The component runs the preview redirect in the browser, so it should work with a static build

**Comment by mortscode** [comment]
It's still not working for me. Here's my setup:

## Prismic Preview Settings:
![image](https://user-images.githubusercontent.com/3239582/132578440-1ce212a8-b596-413d-a8b9-a891daedf63b.png)

I updated all my files to match your branch above (with updated `apiEndpoint` vars for my repo).

## Steps to reproduce
1. Using static adapter, run `npm run build`
2. Navigate to `./build` folder in terminal
3. Run `npx serve` to run a local server on `http://localhost:5000`
4. Open Prismic, make a change to a page, click save, and click Preview -> Local Static Serve

## Results
1. My browser opens a new tab with a tokenized URL, but quickly redirects to `/` (despite having Link Resolver set to `/preview`)
2. Same result whether I'm making changes to `home` or a dynamic page like `/about` or `/offerings`
3. Seemingly the same issue if I use the netlify adapter and push to a netlify.app server

**Comment by mortscode** [comment]
I think I might be failing to fully understand the link resolver and how to protect against the redirect.

**Comment by mortscode** [comment]
If I click Preview->Local (`npm run dev` on `localhost:3000`), a `console.log(session)` on the `[uid].svelte` route, it seems both the `previewToken`, and `documentId` are coming back null.

![image](https://user-images.githubusercontent.com/3239582/132588380-e371f5c5-34d0-43e2-80d7-9b14eeb48b81.png)

It's odd that the Preview functionality works as expected in this situation.

**Comment by samlfair** [comment]
@mortscode I think the problem is that `adapter-static` prerenders the redirect. I'm trying to disable prerender for the preview page, but I can't figure out how to do it. I'll take a look again tomorrow.

**Comment by samlfair** [comment]
Hey @mortscode,

I got this working with `npx serve`, locally, by moving the previewing from the `load()` function to an `onMount()` function. This requires fetching the cookie manually in a browser environment, so it's a bit more complicated. I'll probably try to refactor it later. Let me know if this works for you:

https://github.com/samlfair/svelte-tutorial/compare/update-test

**Comment by samlfair** [comment]
A little more detail:

This is the updated script for the preview component:
```svelte
<script>
    import Prismic from '@prismicio/client'
    import {goto} from '$app/navigation'
    import {onMount} from "svelte"

    const linkResolver = (doc) => '/' + doc.uid // Update this for your site structure
    const apiEndpoint = 'https://svelte-tutorial.cdn.prismic.io/api/v2' // Update this
    const client = Prismic.client(apiEndpoint)

    onMount(async () => {
      const urlParams = new URLSearchParams(window.location.search);
      const token = urlParams.get("token")
      const documentId = urlParams.get("documentId")
      const redirect = await client.getPreviewResolver(token, documentId).resolve(linkResolver, '/') // This generates the URL of the preview document
      await goto(redirect) // This does a client-side redirect to that URL
  })
</script>
```

Since all of the preview functionality happens client-side, you should be fine to delete `/src/hooks/index.js`. (Or at least the relevant `getSession()` code.) Just be sure to remove the references to `session` in your `load()` functions.

Then, on all of your pages, you need to fetch the cookie. This is how I am doing it:
```svelte
<script context="module">
  import Client from './../../utils/client'
  import PrismicDom from 'prismic-dom'
  import { browser } from "$app/env" // This is a SvelteKit utility, equal to `true` or `false` based on whether you're in the browser

  export async function load({ page }) {
    const { uid } = page.params
    const document = browser
      ? await Client(window.document.cookie).getByUID('page', uid ) // If you're in the browser, pass a cookie to the client
      : await Client().getByUID('page', uid )  // If you're not in the browser (prerendering) don't worry about the cookie
    return {
      props: {
        document,
        uid
      }
    };
  }
</script>
```
In the forthcoming v6 of the Prismic client, I believe the queries fetch the cookie automatically, so this might get a little easier. I'm working on that implementation right now.

Let me know if this helps, or if you're still getting errors.

**Comment by mortscode** [comment]
Hey @samlfair, thanks for working on this! I implemented it and it feels like we're getting somewhere now. My problem now is that my pages all seem to load the unpublished versions of the pages on the regular staging site rather than the published version.

### Preview
Let's use the About page as an example (a `[uid].svelte` route): 
- If I make a change and click the "Preview 👁️ " button in Prismic, it opens my local server (`localhost:5000`) at the `/preview/[long-uid]` route and then redirects to `/about` as expected(?).
- The content on the page reflects the unpublished changes that I had made.

### The Problem
The problem is that if I open the server at `localhost:5000/about` without clicking on the "Preview" button: 
- The content on the page also reflects the unpublished changes.
- My hope would be that I would only see the unpublished changes when clicking the "Preview" button.

Any thoughts?

**Comment by samlfair** [comment]
Hey @mortscode,

I think the problem is just that you need to exit the preview session. Normally, if you have the Prismic Toolbar on your site, this is done by clicking the "x" on the toolbar button. However, sometimes this doesn't work, and in your browser you have to go into Dev Tools > Application > Cookies > localhost:5000 and delete the preview cookies. Then it should go back to the published content. Let me know if that works!

PS: I'm offline until Monday, but I'll check in when I'm back.

Sam

**Comment by mortscode** [comment]
Ah! Makes sense.

Can confirm that when i close the Prismic module in the bottom left corner, the content falls back to the published version.

I think this is going to work great!

Thanks @samlfair, I'll reach out if I run into any more hangups.
